version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    env_file:
      - .env

  api:
    build:
      context: ../
      dockerfile: ./docker/quick_vac/Dockerfile
    command: uvicorn app.service:app --reload --proxy-headers --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - "..:/opt/quick_vac"
    environment:
      APP_ENDPOINT: ${APP_ENDPOINT}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      APP_ORIGINS: ${APP_ORIGINS}
      DATABASE_DSN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      ASYNC_DATABASE_DSN: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
