name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_IMAGE: zetoqqq/quick_vac_backend_api:${{ github.sha }}
      RELEASE_IMAGE: zetoqqq/quick_vac_backend_api:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.TEST_IMAGE }} -f docker/quick_vac/Dockerfile .
          docker tag ${{ env.TEST_IMAGE }} ${{ env.RELEASE_IMAGE }}

      - name: Push Docker image
        run: |
          docker push ${{ env.TEST_IMAGE }}
          docker push ${{ env.RELEASE_IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: ssh deploy@194.113.35.10 "cd /home/zeto/deploy && docker-compose pull api && docker-compose up -d"
